// Mocks generated by Mockito 5.4.4 from annotations
// in pachinko_game/test/widgets/pachinko_board_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:ui' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:pachinko_game/models/level.dart' as _i4;
import 'package:pachinko_game/models/peg.dart' as _i6;
import 'package:pachinko_game/models/slot.dart' as _i7;
import 'package:vector_math/vector_math_64.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeVector2_0 extends _i1.SmartFake implements _i2.Vector2 {
  _FakeVector2_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeColor_1 extends _i1.SmartFake implements _i3.Color {
  _FakeColor_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRect_2 extends _i1.SmartFake implements _i3.Rect {
  _FakeRect_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Level].
///
/// See the documentation for Mockito's code generation for more information.
class MockLevel extends _i1.Mock implements _i4.Level {
  MockLevel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get levelNumber => (super.noSuchMethod(
        Invocation.getter(#levelNumber),
        returnValue: 0,
      ) as int);

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  List<_i6.Peg> get pegs => (super.noSuchMethod(
        Invocation.getter(#pegs),
        returnValue: <_i6.Peg>[],
      ) as List<_i6.Peg>);

  @override
  List<_i7.Slot> get slots => (super.noSuchMethod(
        Invocation.getter(#slots),
        returnValue: <_i7.Slot>[],
      ) as List<_i7.Slot>);

  @override
  List<_i6.Peg> get specialPegs => (super.noSuchMethod(
        Invocation.getter(#specialPegs),
        returnValue: <_i6.Peg>[],
      ) as List<_i6.Peg>);

  @override
  double get boardWidth => (super.noSuchMethod(
        Invocation.getter(#boardWidth),
        returnValue: 0.0,
      ) as double);

  @override
  double get boardHeight => (super.noSuchMethod(
        Invocation.getter(#boardHeight),
        returnValue: 0.0,
      ) as double);

  @override
  bool get allSpecialPegsHit => (super.noSuchMethod(
        Invocation.getter(#allSpecialPegsHit),
        returnValue: false,
      ) as bool);

  @override
  double get launchX => (super.noSuchMethod(
        Invocation.getter(#launchX),
        returnValue: 0.0,
      ) as double);

  @override
  double get launchY => (super.noSuchMethod(
        Invocation.getter(#launchY),
        returnValue: 0.0,
      ) as double);

  @override
  void reset() => super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Slot].
///
/// See the documentation for Mockito's code generation for more information.
class MockSlot extends _i1.Mock implements _i7.Slot {
  MockSlot() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Vector2 get position => (super.noSuchMethod(
        Invocation.getter(#position),
        returnValue: _FakeVector2_0(
          this,
          Invocation.getter(#position),
        ),
      ) as _i2.Vector2);

  @override
  set position(_i2.Vector2? _position) => super.noSuchMethod(
        Invocation.setter(
          #position,
          _position,
        ),
        returnValueForMissingStub: null,
      );

  @override
  double get width => (super.noSuchMethod(
        Invocation.getter(#width),
        returnValue: 0.0,
      ) as double);

  @override
  set width(double? _width) => super.noSuchMethod(
        Invocation.setter(
          #width,
          _width,
        ),
        returnValueForMissingStub: null,
      );

  @override
  double get height => (super.noSuchMethod(
        Invocation.getter(#height),
        returnValue: 0.0,
      ) as double);

  @override
  set height(double? _height) => super.noSuchMethod(
        Invocation.setter(
          #height,
          _height,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get pointValue => (super.noSuchMethod(
        Invocation.getter(#pointValue),
        returnValue: 0,
      ) as int);

  @override
  set pointValue(int? _pointValue) => super.noSuchMethod(
        Invocation.setter(
          #pointValue,
          _pointValue,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Color get color => (super.noSuchMethod(
        Invocation.getter(#color),
        returnValue: _FakeColor_1(
          this,
          Invocation.getter(#color),
        ),
      ) as _i3.Color);

  @override
  set color(_i3.Color? _color) => super.noSuchMethod(
        Invocation.setter(
          #color,
          _color,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get ballCount => (super.noSuchMethod(
        Invocation.getter(#ballCount),
        returnValue: 0,
      ) as int);

  @override
  set ballCount(int? _ballCount) => super.noSuchMethod(
        Invocation.setter(
          #ballCount,
          _ballCount,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Rect get bounds => (super.noSuchMethod(
        Invocation.getter(#bounds),
        returnValue: _FakeRect_2(
          this,
          Invocation.getter(#bounds),
        ),
      ) as _i3.Rect);

  @override
  double get centerX => (super.noSuchMethod(
        Invocation.getter(#centerX),
        returnValue: 0.0,
      ) as double);

  @override
  double get centerY => (super.noSuchMethod(
        Invocation.getter(#centerY),
        returnValue: 0.0,
      ) as double);

  @override
  double get left => (super.noSuchMethod(
        Invocation.getter(#left),
        returnValue: 0.0,
      ) as double);

  @override
  double get right => (super.noSuchMethod(
        Invocation.getter(#right),
        returnValue: 0.0,
      ) as double);

  @override
  double get top => (super.noSuchMethod(
        Invocation.getter(#top),
        returnValue: 0.0,
      ) as double);

  @override
  double get bottom => (super.noSuchMethod(
        Invocation.getter(#bottom),
        returnValue: 0.0,
      ) as double);

  @override
  bool containsPoint(_i2.Vector2? point) => (super.noSuchMethod(
        Invocation.method(
          #containsPoint,
          [point],
        ),
        returnValue: false,
      ) as bool);

  @override
  void addBall() => super.noSuchMethod(
        Invocation.method(
          #addBall,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void reset() => super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
