// Mocks generated by Mockito 5.4.4 from annotations
// in pachinko_game/test/services/game_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:ui' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:pachinko_game/models/ball.dart' as _i4;
import 'package:pachinko_game/models/ball_launcher.dart' as _i9;
import 'package:pachinko_game/models/game_state.dart' as _i7;
import 'package:pachinko_game/models/level.dart' as _i10;
import 'package:pachinko_game/models/peg.dart' as _i5;
import 'package:pachinko_game/models/slot.dart' as _i6;
import 'package:pachinko_game/services/physics_engine.dart' as _i3;
import 'package:vector_math/vector_math_64.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeVector2_0 extends _i1.SmartFake implements _i2.Vector2 {
  _FakeVector2_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PhysicsEngine].
///
/// See the documentation for Mockito's code generation for more information.
class MockPhysicsEngine extends _i1.Mock implements _i3.PhysicsEngine {
  MockPhysicsEngine() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void updateBalls(
    List<_i4.Ball>? balls,
    double? deltaTime,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #updateBalls,
          [
            balls,
            deltaTime,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i5.Peg> checkPegCollisions(
    List<_i4.Ball>? balls,
    List<_i5.Peg>? pegs,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkPegCollisions,
          [
            balls,
            pegs,
          ],
        ),
        returnValue: <_i5.Peg>[],
      ) as List<_i5.Peg>);

  @override
  List<_i6.Slot> checkSlotCollisions(
    List<_i4.Ball>? balls,
    List<_i6.Slot>? slots,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkSlotCollisions,
          [
            balls,
            slots,
          ],
        ),
        returnValue: <_i6.Slot>[],
      ) as List<_i6.Slot>);

  @override
  _i2.Vector2 calculateLaunchVelocity(
    _i2.Vector2? startPosition,
    _i2.Vector2? targetPosition,
    double? force,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateLaunchVelocity,
          [
            startPosition,
            targetPosition,
            force,
          ],
        ),
        returnValue: _FakeVector2_0(
          this,
          Invocation.method(
            #calculateLaunchVelocity,
            [
              startPosition,
              targetPosition,
              force,
            ],
          ),
        ),
      ) as _i2.Vector2);

  @override
  bool isValidLaunchAngle(double? angle) => (super.noSuchMethod(
        Invocation.method(
          #isValidLaunchAngle,
          [angle],
        ),
        returnValue: false,
      ) as bool);

  @override
  double calculateTrajectoryMaxHeight(
    _i2.Vector2? launchVelocity,
    _i2.Vector2? startPosition,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateTrajectoryMaxHeight,
          [
            launchVelocity,
            startPosition,
          ],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  List<_i2.Vector2> calculateTrajectoryPoints(
    _i2.Vector2? startPosition,
    _i2.Vector2? launchVelocity,
    int? numPoints,
    double? timeStep,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateTrajectoryPoints,
          [
            startPosition,
            launchVelocity,
            numPoints,
            timeStep,
          ],
        ),
        returnValue: <_i2.Vector2>[],
      ) as List<_i2.Vector2>);
}

/// A class which mocks [GameState].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameState extends _i1.Mock implements _i7.GameState {
  MockGameState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get currentLevelNumber => (super.noSuchMethod(
        Invocation.getter(#currentLevelNumber),
        returnValue: 0,
      ) as int);

  @override
  int get score => (super.noSuchMethod(
        Invocation.getter(#score),
        returnValue: 0,
      ) as int);

  @override
  int get ballsRemaining => (super.noSuchMethod(
        Invocation.getter(#ballsRemaining),
        returnValue: 0,
      ) as int);

  @override
  int get totalBalls => (super.noSuchMethod(
        Invocation.getter(#totalBalls),
        returnValue: 0,
      ) as int);

  @override
  List<_i4.Ball> get activeBalls => (super.noSuchMethod(
        Invocation.getter(#activeBalls),
        returnValue: <_i4.Ball>[],
      ) as List<_i4.Ball>);

  @override
  _i7.GamePhase get phase => (super.noSuchMethod(
        Invocation.getter(#phase),
        returnValue: _i7.GamePhase.loading,
      ) as _i7.GamePhase);

  @override
  bool get specialBonusTriggered => (super.noSuchMethod(
        Invocation.getter(#specialBonusTriggered),
        returnValue: false,
      ) as bool);

  @override
  bool get canLaunchBall => (super.noSuchMethod(
        Invocation.getter(#canLaunchBall),
        returnValue: false,
      ) as bool);

  @override
  bool get isGameOver => (super.noSuchMethod(
        Invocation.getter(#isGameOver),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void loadLevel(int? levelNumber) => super.noSuchMethod(
        Invocation.method(
          #loadLevel,
          [levelNumber],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void startNewGame({int? level = 1}) => super.noSuchMethod(
        Invocation.method(
          #startNewGame,
          [],
          {#level: level},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void launchBall(_i4.Ball? ball) => super.noSuchMethod(
        Invocation.method(
          #launchBall,
          [ball],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addScore(int? points) => super.noSuchMethod(
        Invocation.method(
          #addScore,
          [points],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeBall(_i4.Ball? ball) => super.noSuchMethod(
        Invocation.method(
          #removeBall,
          [ball],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void triggerSpecialBonus() => super.noSuchMethod(
        Invocation.method(
          #triggerSpecialBonus,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void nextLevel() => super.noSuchMethod(
        Invocation.method(
          #nextLevel,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resetLevel() => super.noSuchMethod(
        Invocation.method(
          #resetLevel,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void pauseGame() => super.noSuchMethod(
        Invocation.method(
          #pauseGame,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resumeGame() => super.noSuchMethod(
        Invocation.method(
          #resumeGame,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updatePhase(_i7.GamePhase? newPhase) => super.noSuchMethod(
        Invocation.method(
          #updatePhase,
          [newPhase],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [BallLauncher].
///
/// See the documentation for Mockito's code generation for more information.
class MockBallLauncher extends _i1.Mock implements _i9.BallLauncher {
  MockBallLauncher() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.LaunchPhase get phase => (super.noSuchMethod(
        Invocation.getter(#phase),
        returnValue: _i9.LaunchPhase.ready,
      ) as _i9.LaunchPhase);

  @override
  double get launchPower => (super.noSuchMethod(
        Invocation.getter(#launchPower),
        returnValue: 0.0,
      ) as double);

  @override
  double get maxPower => (super.noSuchMethod(
        Invocation.getter(#maxPower),
        returnValue: 0.0,
      ) as double);

  @override
  void startCharging() => super.noSuchMethod(
        Invocation.method(
          #startCharging,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateCharging(double? power) => super.noSuchMethod(
        Invocation.method(
          #updateCharging,
          [power],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool updateBallPath(double? deltaTime) => (super.noSuchMethod(
        Invocation.method(
          #updateBallPath,
          [deltaTime],
        ),
        returnValue: false,
      ) as bool);

  @override
  void reset() => super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i2.Vector2> getLaunchPath() => (super.noSuchMethod(
        Invocation.method(
          #getLaunchPath,
          [],
        ),
        returnValue: <_i2.Vector2>[],
      ) as List<_i2.Vector2>);
}

/// A class which mocks [Level].
///
/// See the documentation for Mockito's code generation for more information.
class MockLevel extends _i1.Mock implements _i10.Level {
  MockLevel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get levelNumber => (super.noSuchMethod(
        Invocation.getter(#levelNumber),
        returnValue: 0,
      ) as int);

  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  List<_i5.Peg> get pegs => (super.noSuchMethod(
        Invocation.getter(#pegs),
        returnValue: <_i5.Peg>[],
      ) as List<_i5.Peg>);

  @override
  List<_i6.Slot> get slots => (super.noSuchMethod(
        Invocation.getter(#slots),
        returnValue: <_i6.Slot>[],
      ) as List<_i6.Slot>);

  @override
  List<_i5.Peg> get specialPegs => (super.noSuchMethod(
        Invocation.getter(#specialPegs),
        returnValue: <_i5.Peg>[],
      ) as List<_i5.Peg>);

  @override
  double get boardWidth => (super.noSuchMethod(
        Invocation.getter(#boardWidth),
        returnValue: 0.0,
      ) as double);

  @override
  double get boardHeight => (super.noSuchMethod(
        Invocation.getter(#boardHeight),
        returnValue: 0.0,
      ) as double);

  @override
  bool get allSpecialPegsHit => (super.noSuchMethod(
        Invocation.getter(#allSpecialPegsHit),
        returnValue: false,
      ) as bool);

  @override
  double get launchX => (super.noSuchMethod(
        Invocation.getter(#launchX),
        returnValue: 0.0,
      ) as double);

  @override
  double get launchY => (super.noSuchMethod(
        Invocation.getter(#launchY),
        returnValue: 0.0,
      ) as double);

  @override
  void reset() => super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
