// Mocks generated by Mockito 5.4.4 from annotations
// in pachinko_game/test/services/physics_engine_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:ui' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pachinko_game/models/ball.dart' as _i4;
import 'package:pachinko_game/models/peg.dart' as _i5;
import 'package:pachinko_game/models/slot.dart' as _i6;
import 'package:vector_math/vector_math_64.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeVector2_0 extends _i1.SmartFake implements _i2.Vector2 {
  _FakeVector2_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeColor_1 extends _i1.SmartFake implements _i3.Color {
  _FakeColor_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRect_2 extends _i1.SmartFake implements _i3.Rect {
  _FakeRect_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Ball].
///
/// See the documentation for Mockito's code generation for more information.
class MockBall extends _i1.Mock implements _i4.Ball {
  MockBall() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Vector2 get position => (super.noSuchMethod(
        Invocation.getter(#position),
        returnValue: _FakeVector2_0(
          this,
          Invocation.getter(#position),
        ),
      ) as _i2.Vector2);

  @override
  set position(_i2.Vector2? _position) => super.noSuchMethod(
        Invocation.setter(
          #position,
          _position,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Vector2 get velocity => (super.noSuchMethod(
        Invocation.getter(#velocity),
        returnValue: _FakeVector2_0(
          this,
          Invocation.getter(#velocity),
        ),
      ) as _i2.Vector2);

  @override
  set velocity(_i2.Vector2? _velocity) => super.noSuchMethod(
        Invocation.setter(
          #velocity,
          _velocity,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Vector2 get acceleration => (super.noSuchMethod(
        Invocation.getter(#acceleration),
        returnValue: _FakeVector2_0(
          this,
          Invocation.getter(#acceleration),
        ),
      ) as _i2.Vector2);

  @override
  set acceleration(_i2.Vector2? _acceleration) => super.noSuchMethod(
        Invocation.setter(
          #acceleration,
          _acceleration,
        ),
        returnValueForMissingStub: null,
      );

  @override
  double get radius => (super.noSuchMethod(
        Invocation.getter(#radius),
        returnValue: 0.0,
      ) as double);

  @override
  set radius(double? _radius) => super.noSuchMethod(
        Invocation.setter(
          #radius,
          _radius,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Color get color => (super.noSuchMethod(
        Invocation.getter(#color),
        returnValue: _FakeColor_1(
          this,
          Invocation.getter(#color),
        ),
      ) as _i3.Color);

  @override
  set color(_i3.Color? _color) => super.noSuchMethod(
        Invocation.setter(
          #color,
          _color,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get isActive => (super.noSuchMethod(
        Invocation.getter(#isActive),
        returnValue: false,
      ) as bool);

  @override
  set isActive(bool? _isActive) => super.noSuchMethod(
        Invocation.setter(
          #isActive,
          _isActive,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasLanded => (super.noSuchMethod(
        Invocation.getter(#hasLanded),
        returnValue: false,
      ) as bool);

  @override
  set hasLanded(bool? _hasLanded) => super.noSuchMethod(
        Invocation.setter(
          #hasLanded,
          _hasLanded,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get isOutOfBounds => (super.noSuchMethod(
        Invocation.getter(#isOutOfBounds),
        returnValue: false,
      ) as bool);

  @override
  void update(double? deltaTime) => super.noSuchMethod(
        Invocation.method(
          #update,
          [deltaTime],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void applyImpulse(_i2.Vector2? impulse) => super.noSuchMethod(
        Invocation.method(
          #applyImpulse,
          [impulse],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void reset(_i2.Vector2? newPosition) => super.noSuchMethod(
        Invocation.method(
          #reset,
          [newPosition],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Peg].
///
/// See the documentation for Mockito's code generation for more information.
class MockPeg extends _i1.Mock implements _i5.Peg {
  MockPeg() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Vector2 get position => (super.noSuchMethod(
        Invocation.getter(#position),
        returnValue: _FakeVector2_0(
          this,
          Invocation.getter(#position),
        ),
      ) as _i2.Vector2);

  @override
  set position(_i2.Vector2? _position) => super.noSuchMethod(
        Invocation.setter(
          #position,
          _position,
        ),
        returnValueForMissingStub: null,
      );

  @override
  double get radius => (super.noSuchMethod(
        Invocation.getter(#radius),
        returnValue: 0.0,
      ) as double);

  @override
  set radius(double? _radius) => super.noSuchMethod(
        Invocation.setter(
          #radius,
          _radius,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.PegType get type => (super.noSuchMethod(
        Invocation.getter(#type),
        returnValue: _i5.PegType.normal,
      ) as _i5.PegType);

  @override
  set type(_i5.PegType? _type) => super.noSuchMethod(
        Invocation.setter(
          #type,
          _type,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Color get color => (super.noSuchMethod(
        Invocation.getter(#color),
        returnValue: _FakeColor_1(
          this,
          Invocation.getter(#color),
        ),
      ) as _i3.Color);

  @override
  set color(_i3.Color? _color) => super.noSuchMethod(
        Invocation.setter(
          #color,
          _color,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get isHighlighted => (super.noSuchMethod(
        Invocation.getter(#isHighlighted),
        returnValue: false,
      ) as bool);

  @override
  set isHighlighted(bool? _isHighlighted) => super.noSuchMethod(
        Invocation.setter(
          #isHighlighted,
          _isHighlighted,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasBeenHit => (super.noSuchMethod(
        Invocation.getter(#hasBeenHit),
        returnValue: false,
      ) as bool);

  @override
  set hasBeenHit(bool? _hasBeenHit) => super.noSuchMethod(
        Invocation.setter(
          #hasBeenHit,
          _hasBeenHit,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get isAnimating => (super.noSuchMethod(
        Invocation.getter(#isAnimating),
        returnValue: false,
      ) as bool);

  @override
  set isAnimating(bool? _isAnimating) => super.noSuchMethod(
        Invocation.setter(
          #isAnimating,
          _isAnimating,
        ),
        returnValueForMissingStub: null,
      );

  @override
  double get pulseProgress => (super.noSuchMethod(
        Invocation.getter(#pulseProgress),
        returnValue: 0.0,
      ) as double);

  @override
  set pulseProgress(double? _pulseProgress) => super.noSuchMethod(
        Invocation.setter(
          #pulseProgress,
          _pulseProgress,
        ),
        returnValueForMissingStub: null,
      );

  @override
  double get shimmerIntensity => (super.noSuchMethod(
        Invocation.getter(#shimmerIntensity),
        returnValue: 0.0,
      ) as double);

  @override
  set shimmerIntensity(double? _shimmerIntensity) => super.noSuchMethod(
        Invocation.setter(
          #shimmerIntensity,
          _shimmerIntensity,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Color get renderColor => (super.noSuchMethod(
        Invocation.getter(#renderColor),
        returnValue: _FakeColor_1(
          this,
          Invocation.getter(#renderColor),
        ),
      ) as _i3.Color);

  @override
  double get pulseGlowRadius => (super.noSuchMethod(
        Invocation.getter(#pulseGlowRadius),
        returnValue: 0.0,
      ) as double);

  @override
  double get pulseGlowOpacity => (super.noSuchMethod(
        Invocation.getter(#pulseGlowOpacity),
        returnValue: 0.0,
      ) as double);

  @override
  bool checkCollision(
    _i2.Vector2? ballPosition,
    double? ballRadius,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #checkCollision,
          [
            ballPosition,
            ballRadius,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i2.Vector2 getCollisionNormal(_i2.Vector2? ballPosition) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCollisionNormal,
          [ballPosition],
        ),
        returnValue: _FakeVector2_0(
          this,
          Invocation.method(
            #getCollisionNormal,
            [ballPosition],
          ),
        ),
      ) as _i2.Vector2);

  @override
  void onHit() => super.noSuchMethod(
        Invocation.method(
          #onHit,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void reset() => super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateAnimation(double? deltaTime) => super.noSuchMethod(
        Invocation.method(
          #updateAnimation,
          [deltaTime],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [Slot].
///
/// See the documentation for Mockito's code generation for more information.
class MockSlot extends _i1.Mock implements _i6.Slot {
  MockSlot() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Vector2 get position => (super.noSuchMethod(
        Invocation.getter(#position),
        returnValue: _FakeVector2_0(
          this,
          Invocation.getter(#position),
        ),
      ) as _i2.Vector2);

  @override
  set position(_i2.Vector2? _position) => super.noSuchMethod(
        Invocation.setter(
          #position,
          _position,
        ),
        returnValueForMissingStub: null,
      );

  @override
  double get width => (super.noSuchMethod(
        Invocation.getter(#width),
        returnValue: 0.0,
      ) as double);

  @override
  set width(double? _width) => super.noSuchMethod(
        Invocation.setter(
          #width,
          _width,
        ),
        returnValueForMissingStub: null,
      );

  @override
  double get height => (super.noSuchMethod(
        Invocation.getter(#height),
        returnValue: 0.0,
      ) as double);

  @override
  set height(double? _height) => super.noSuchMethod(
        Invocation.setter(
          #height,
          _height,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get pointValue => (super.noSuchMethod(
        Invocation.getter(#pointValue),
        returnValue: 0,
      ) as int);

  @override
  set pointValue(int? _pointValue) => super.noSuchMethod(
        Invocation.setter(
          #pointValue,
          _pointValue,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Color get color => (super.noSuchMethod(
        Invocation.getter(#color),
        returnValue: _FakeColor_1(
          this,
          Invocation.getter(#color),
        ),
      ) as _i3.Color);

  @override
  set color(_i3.Color? _color) => super.noSuchMethod(
        Invocation.setter(
          #color,
          _color,
        ),
        returnValueForMissingStub: null,
      );

  @override
  int get ballCount => (super.noSuchMethod(
        Invocation.getter(#ballCount),
        returnValue: 0,
      ) as int);

  @override
  set ballCount(int? _ballCount) => super.noSuchMethod(
        Invocation.setter(
          #ballCount,
          _ballCount,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Rect get bounds => (super.noSuchMethod(
        Invocation.getter(#bounds),
        returnValue: _FakeRect_2(
          this,
          Invocation.getter(#bounds),
        ),
      ) as _i3.Rect);

  @override
  double get centerX => (super.noSuchMethod(
        Invocation.getter(#centerX),
        returnValue: 0.0,
      ) as double);

  @override
  double get centerY => (super.noSuchMethod(
        Invocation.getter(#centerY),
        returnValue: 0.0,
      ) as double);

  @override
  double get left => (super.noSuchMethod(
        Invocation.getter(#left),
        returnValue: 0.0,
      ) as double);

  @override
  double get right => (super.noSuchMethod(
        Invocation.getter(#right),
        returnValue: 0.0,
      ) as double);

  @override
  double get top => (super.noSuchMethod(
        Invocation.getter(#top),
        returnValue: 0.0,
      ) as double);

  @override
  double get bottom => (super.noSuchMethod(
        Invocation.getter(#bottom),
        returnValue: 0.0,
      ) as double);

  @override
  bool containsPoint(_i2.Vector2? point) => (super.noSuchMethod(
        Invocation.method(
          #containsPoint,
          [point],
        ),
        returnValue: false,
      ) as bool);

  @override
  void addBall() => super.noSuchMethod(
        Invocation.method(
          #addBall,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void reset() => super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
