// Mocks generated by Mockito 5.4.4 from annotations
// in pachinko_game/test/screens/achievements_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:ui' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pachinko_game/models/achievement.dart' as _i3;
import 'package:pachinko_game/services/achievement_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AchievementService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAchievementService extends _i1.Mock
    implements _i2.AchievementService {
  MockAchievementService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set onAchievementUnlocked(
          void Function(_i3.Achievement)? _onAchievementUnlocked) =>
      super.noSuchMethod(
        Invocation.setter(
          #onAchievementUnlocked,
          _onAchievementUnlocked,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void trackBallLaunched() => super.noSuchMethod(
        Invocation.method(
          #trackBallLaunched,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void trackLevelComplete(int? level) => super.noSuchMethod(
        Invocation.method(
          #trackLevelComplete,
          [level],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void trackLevelScore(
    int? level,
    int? score,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #trackLevelScore,
          [
            level,
            score,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void trackSingleBallScore(int? score) => super.noSuchMethod(
        Invocation.method(
          #trackSingleBallScore,
          [score],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void trackAllSpecialPegsHit() => super.noSuchMethod(
        Invocation.method(
          #trackAllSpecialPegsHit,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void trackSpecialBonus() => super.noSuchMethod(
        Invocation.method(
          #trackSpecialBonus,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void trackSpecialPegCombo(int? count) => super.noSuchMethod(
        Invocation.method(
          #trackSpecialPegCombo,
          [count],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void trackEdgeSlot() => super.noSuchMethod(
        Invocation.method(
          #trackEdgeSlot,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void checkCollectionAchievements() => super.noSuchMethod(
        Invocation.method(
          #checkCollectionAchievements,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i3.Achievement> getAllAchievements() => (super.noSuchMethod(
        Invocation.method(
          #getAllAchievements,
          [],
        ),
        returnValue: <_i3.Achievement>[],
      ) as List<_i3.Achievement>);

  @override
  List<_i3.Achievement> getUnlockedAchievements() => (super.noSuchMethod(
        Invocation.method(
          #getUnlockedAchievements,
          [],
        ),
        returnValue: <_i3.Achievement>[],
      ) as List<_i3.Achievement>);

  @override
  List<_i3.Achievement> getLockedAchievements() => (super.noSuchMethod(
        Invocation.method(
          #getLockedAchievements,
          [],
        ),
        returnValue: <_i3.Achievement>[],
      ) as List<_i3.Achievement>);

  @override
  int getTotalPoints() => (super.noSuchMethod(
        Invocation.method(
          #getTotalPoints,
          [],
        ),
        returnValue: 0,
      ) as int);

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
