// Mocks generated by Mockito 5.4.4 from annotations
// in pachinko_game/test/screens/high_scores_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pachinko_game/models/high_score.dart' as _i4;
import 'package:pachinko_game/services/storage_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i2.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveHighScore(
    int? level,
    int? score,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveHighScore,
          [
            level,
            score,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.HighScore>> getHighScores(int? level) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHighScores,
          [level],
        ),
        returnValue: _i3.Future<List<_i4.HighScore>>.value(<_i4.HighScore>[]),
      ) as _i3.Future<List<_i4.HighScore>>);

  @override
  _i3.Future<int> getTotalScore() => (super.noSuchMethod(
        Invocation.method(
          #getTotalScore,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<_i4.HighScore?> getBestScore(int? level) => (super.noSuchMethod(
        Invocation.method(
          #getBestScore,
          [level],
        ),
        returnValue: _i3.Future<_i4.HighScore?>.value(),
      ) as _i3.Future<_i4.HighScore?>);

  @override
  _i3.Future<void> clearData() => (super.noSuchMethod(
        Invocation.method(
          #clearData,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
