// Mocks generated by Mockito 5.4.4 from annotations
// in pachinko_game/test/screens/menu_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:ui' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pachinko_game/models/ball.dart' as _i7;
import 'package:pachinko_game/models/ball_launcher.dart' as _i4;
import 'package:pachinko_game/models/game_state.dart' as _i2;
import 'package:pachinko_game/services/game_manager.dart' as _i5;
import 'package:pachinko_game/services/physics_engine.dart' as _i3;
import 'package:vector_math/vector_math_64.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGameState_0 extends _i1.SmartFake implements _i2.GameState {
  _FakeGameState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePhysicsEngine_1 extends _i1.SmartFake implements _i3.PhysicsEngine {
  _FakePhysicsEngine_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBallLauncher_2 extends _i1.SmartFake implements _i4.BallLauncher {
  _FakeBallLauncher_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GameManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameManager extends _i1.Mock implements _i5.GameManager {
  MockGameManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GameState get gameState => (super.noSuchMethod(
        Invocation.getter(#gameState),
        returnValue: _FakeGameState_0(
          this,
          Invocation.getter(#gameState),
        ),
      ) as _i2.GameState);

  @override
  _i3.PhysicsEngine get physicsEngine => (super.noSuchMethod(
        Invocation.getter(#physicsEngine),
        returnValue: _FakePhysicsEngine_1(
          this,
          Invocation.getter(#physicsEngine),
        ),
      ) as _i3.PhysicsEngine);

  @override
  _i4.BallLauncher get ballLauncher => (super.noSuchMethod(
        Invocation.getter(#ballLauncher),
        returnValue: _FakeBallLauncher_2(
          this,
          Invocation.getter(#ballLauncher),
        ),
      ) as _i4.BallLauncher);

  @override
  bool get isRunning => (super.noSuchMethod(
        Invocation.getter(#isRunning),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void startGame({int? level = 1}) => super.noSuchMethod(
        Invocation.method(
          #startGame,
          [],
          {#level: level},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void pauseGame() => super.noSuchMethod(
        Invocation.method(
          #pauseGame,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resumeGame() => super.noSuchMethod(
        Invocation.method(
          #resumeGame,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resetGame() => super.noSuchMethod(
        Invocation.method(
          #resetGame,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void startLaunchCharging() => super.noSuchMethod(
        Invocation.method(
          #startLaunchCharging,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateLaunchPower(double? power) => super.noSuchMethod(
        Invocation.method(
          #updateLaunchPower,
          [power],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void launchBall() => super.noSuchMethod(
        Invocation.method(
          #launchBall,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void nextLevel() => super.noSuchMethod(
        Invocation.method(
          #nextLevel,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void selectLevel(int? levelNumber) => super.noSuchMethod(
        Invocation.method(
          #selectLevel,
          [levelNumber],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [GameState].
///
/// See the documentation for Mockito's code generation for more information.
class MockGameState extends _i1.Mock implements _i2.GameState {
  MockGameState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get currentLevelNumber => (super.noSuchMethod(
        Invocation.getter(#currentLevelNumber),
        returnValue: 0,
      ) as int);

  @override
  int get score => (super.noSuchMethod(
        Invocation.getter(#score),
        returnValue: 0,
      ) as int);

  @override
  int get ballsRemaining => (super.noSuchMethod(
        Invocation.getter(#ballsRemaining),
        returnValue: 0,
      ) as int);

  @override
  int get totalBalls => (super.noSuchMethod(
        Invocation.getter(#totalBalls),
        returnValue: 0,
      ) as int);

  @override
  List<_i7.Ball> get activeBalls => (super.noSuchMethod(
        Invocation.getter(#activeBalls),
        returnValue: <_i7.Ball>[],
      ) as List<_i7.Ball>);

  @override
  _i2.GamePhase get phase => (super.noSuchMethod(
        Invocation.getter(#phase),
        returnValue: _i2.GamePhase.loading,
      ) as _i2.GamePhase);

  @override
  bool get specialBonusTriggered => (super.noSuchMethod(
        Invocation.getter(#specialBonusTriggered),
        returnValue: false,
      ) as bool);

  @override
  bool get canLaunchBall => (super.noSuchMethod(
        Invocation.getter(#canLaunchBall),
        returnValue: false,
      ) as bool);

  @override
  bool get isGameOver => (super.noSuchMethod(
        Invocation.getter(#isGameOver),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void loadLevel(int? levelNumber) => super.noSuchMethod(
        Invocation.method(
          #loadLevel,
          [levelNumber],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void startNewGame({int? level = 1}) => super.noSuchMethod(
        Invocation.method(
          #startNewGame,
          [],
          {#level: level},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void launchBall(_i7.Ball? ball) => super.noSuchMethod(
        Invocation.method(
          #launchBall,
          [ball],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addScore(int? points) => super.noSuchMethod(
        Invocation.method(
          #addScore,
          [points],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeBall(_i7.Ball? ball) => super.noSuchMethod(
        Invocation.method(
          #removeBall,
          [ball],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void triggerSpecialBonus() => super.noSuchMethod(
        Invocation.method(
          #triggerSpecialBonus,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void nextLevel() => super.noSuchMethod(
        Invocation.method(
          #nextLevel,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resetLevel() => super.noSuchMethod(
        Invocation.method(
          #resetLevel,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void pauseGame() => super.noSuchMethod(
        Invocation.method(
          #pauseGame,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void resumeGame() => super.noSuchMethod(
        Invocation.method(
          #resumeGame,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updatePhase(_i2.GamePhase? newPhase) => super.noSuchMethod(
        Invocation.method(
          #updatePhase,
          [newPhase],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [BallLauncher].
///
/// See the documentation for Mockito's code generation for more information.
class MockBallLauncher extends _i1.Mock implements _i4.BallLauncher {
  MockBallLauncher() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.LaunchPhase get phase => (super.noSuchMethod(
        Invocation.getter(#phase),
        returnValue: _i4.LaunchPhase.ready,
      ) as _i4.LaunchPhase);

  @override
  double get launchPower => (super.noSuchMethod(
        Invocation.getter(#launchPower),
        returnValue: 0.0,
      ) as double);

  @override
  double get maxPower => (super.noSuchMethod(
        Invocation.getter(#maxPower),
        returnValue: 0.0,
      ) as double);

  @override
  void startCharging() => super.noSuchMethod(
        Invocation.method(
          #startCharging,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateCharging(double? power) => super.noSuchMethod(
        Invocation.method(
          #updateCharging,
          [power],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool updateBallPath(double? deltaTime) => (super.noSuchMethod(
        Invocation.method(
          #updateBallPath,
          [deltaTime],
        ),
        returnValue: false,
      ) as bool);

  @override
  void reset() => super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i8.Vector2> getLaunchPath() => (super.noSuchMethod(
        Invocation.method(
          #getLaunchPath,
          [],
        ),
        returnValue: <_i8.Vector2>[],
      ) as List<_i8.Vector2>);
}
